# version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: ctwr_new_website_db
    volumes:
      # - ./tmp/db:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    env_file:
      - ".env"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  web:
    build: .
    # command: "./bin/rails server"
    volumes:
      # - .:/app
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - ".env"
volumes:
  postgres_data: {}
  app-storage: {}